


INSERT INTO BOOK (TITLE) VALUES ('book-3');
SET @book1 = LAST_INSERT_ID();
INSERT INTO BOOK (TITLE) VALUES ('book-4');
SET @book2 = LAST_INSERT_ID();




INSERT INTO CUSTOMER (FIRSTNAME,LASTNAME)  VALUES  ('Jens','Mueller');
INSERT INTO CUSTOMER (FIRSTNAME,LASTNAME)  VALUES  ('Steve','Mueller');





